### ISSUE TITLE
operation buttons don't work on runs from the job page

### ISSUE THREAD

**Issue by pancakewaffles** [apsis-scheduler/apsis#211]
It seems it's not possible to do any of the operations ('mark success', 'mark failure', 'rerun') a run directly from the list of runs on the job page, despite the option being present under `Operations`. One has to open the run page for the specific run and then the buttons will work.

To replicate, go to a job, open list of runs, under `operations`, click any of the buttons `Mark Success`, `Mark Failure`, `Rerun`. None of them will work.

**Comment by alexhsamuel** [comment]
Thanks for reporting.

I can't reproduce this with v0.13.1; all operations work when invoked from the job view.  Is this the version you are using?  

What exactly do you mean by "don't work"?  If you click one of the buttons, do you see a modal confirmation dialog?  If you click through the modal, what happens?

Some other things to check:

1. Is there anything untoward in the browser's debug console?
2. Do you see a request and other activity related to the operation in the Apsis server's log?  Something like this:
```
2022-11-04T00:58:26.827 apsis.runs               D transition r84: success → failure
2022-11-04T00:58:26.831 apsis.run_log            I run r84: marked as failure
2022-11-04T00:58:26.836 sanic.access             I 200 POST http://localhost:8080/api/v1/runs/r84/mark/failure (127.0.0.1:56224)
```

**Comment by pancakewaffles** [comment]
Yes I am using 0.13.1.

The buttons for operations are visible in the operations popup when I click the hamburger button.

However, nothing happens when clicking any of the buttons for operations. No modal confirmation shows up.

On Nov 4, 2022, at 12:05 AM, Alex Samuel ***@***.***> wrote:

﻿

Thanks for reporting.

I can't reproduce this with v0.13.1. Is this the version you are using?

What exactly do you mean by "don't work"? Are buttons for operations visible in the operations popup when you click the hamburger button? If you click one of the buttons, do you see a modal confirmation dialog? If you click through the modal, what happens?

**Comment by alexhsamuel** [comment]
Got it.  This is a browser-specific bug, which is why I hadn't noticed it earlier.  Will be fixed in the next release, or do you want a patch release v0.13.2?

**Comment by pancakewaffles** [comment]
Not urgent, let's wait for next release.
