### ISSUE TITLE
ora name error in apsis.py

### ISSUE THREAD

**Issue by pancakewaffles** [apsis-scheduler/apsis#223]
ora was called in https://github.com/alexhsamuel/apsis/blob/master/python/apsis/apsis.py#L165-L169

But you didn't import ora in https://github.com/alexhsamuel/apsis/blob/master/python/apsis/apsis.py#L4

This will stop apsis from starting up if we have a max waiting time.

**Comment by alexhsamuel** [comment]
fixed in https://github.com/alexhsamuel/apsis/releases/tag/v0.14.1
