### ISSUE TITLE
TimeoutWaiting NameError

### ISSUE THREAD

**Issue by pancakewaffles** [apsis-scheduler/apsis#228]
Getting an issue with time out jobs:

```
Traceback (most recent call last):
  File "apsis/apsis.py", line 213, in loop
    raise TimeoutWaiting(
NameError: name 'TimeoutWaiting' is not defined
```

This doesn't crash Apsis, but it raises an error for these jobs timing out.

**Comment by alexhsamuel** [comment]
To be clear, these runs should be transitioned to _error_, though the run log should show the reason correctly, rather than indicating an internal error in Apsis.
