### ISSUE TITLE
Timeout for jobs in "waiting" state

### ISSUE THREAD

**Issue by axwest** [apsis-scheduler/apsis#327]
Can we allow an timeout for jobs in a "waiting" state, which would flip a job from "waiting" to "failure"?  This would help us identify cases where a job is not going to run because its conditions will never be satisfied.

**Comment by alexhsamuel** [comment]
This already exists (except that it transitions to _error_), configurable as `waiting.max_time`. 
https://apsis-scheduler.readthedocs.io/en/latest/config.html#waiting

**Comment by axwest** [comment]
Thanks, Alex.
