### ISSUE TITLE
clockdb advances if Apsis fails to schedule runs and dies at startup

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#368]

**Comment by gusostow** [comment]
Here's a reproducer of the ClockDB getting advanced when there's an exception raised earlier in the score schedule operation.

```
$ sqlite3 apsis.db 'SELECT * FROM clock'
1730149823.27428

$ apsisctl serve --config CONFIG
2024-10-28T21:11:28.851 sanic.root               I Goin' Fast @ http://127.0.0.1:5000
2024-10-28T21:11:28.851 sanic.root               I Goin' Fast @ http://127.0.0.1:5000
2024-10-28T21:11:28.857 apsis.scheduler          C scheduler loop failed
Traceback (most recent call last):
  File "/home/aostow/repos/apsis/python/apsis/scheduler.py", line 126, in loop
    await self.schedule(time + self.__horizon)
  File "/home/aostow/repos/apsis/python/apsis/scheduler.py", line 104, in schedule
    await self.__schedule(time, run)
  File "/home/aostow/repos/apsis/python/apsis/apsis.py", line 490, in schedule
    raise Exception("scheduler failed")
Exception: scheduler failed
2024-10-28T21:11:28.890 apsis.lib.asyn           W task: scheduler_loop
Traceback (most recent call last):
  File "/home/aostow/repos/apsis/python/apsis/scheduler.py", line 126, in loop
    await self.schedule(time + self.__horizon)
  File "/home/aostow/repos/apsis/python/apsis/scheduler.py", line 104, in schedule
    await self.__schedule(time, run)
  File "/home/aostow/repos/apsis/python/apsis/apsis.py", line 490, in schedule
    raise Exception("scheduler failed")
Exception: scheduler failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aostow/repos/apsis/python/apsis/lib/asyn.py", line 111, in done
    _ = task.result()
  File "/home/aostow/repos/apsis/python/apsis/scheduler.py", line 134, in loop
    raise SystemExit(1)
SystemExit: 1

$ sqlite3 apsis.db 'SELECT * FROM clock'
1730149888.8583
```

This is where I inserted the exception:

```diff
diff --git a/python/apsis/apsis.py b/python/apsis/apsis.py
index f7ed4a87..b550e4df 100644
--- a/python/apsis/apsis.py
+++ b/python/apsis/apsis.py
@@ -487,6 +487,8 @@ class Apsis:
         """
         time = None if time is None else Time(time)
 
+        raise Exception("scheduler failed")
+
         self.run_store.add(run)
         if not self.__prepare_run(run):
             return run
```

**Comment by alexhsamuel** [comment]
OK a bit confusion here, including on my part.  Here's the story.

The clock DB contains Apsis's "now", in the sense of the horizon at which _scheduled_ runs become due and proceed to _waiting_.  This transition is handled by the `Scheduled` component.

The component that actually creates new runs from schedules, `Scheduler`, has its own internal time horizon.  When Apsis starts, this is initialized to the same horizon as `ScheduledRuns`, from the clock DB.  Then, Apsis starts the scheduler loop, which creates runs into the future, as specified by the schedule horizon config.

When Apsis restarts, the `Scheduler` component is reset to the clock DB, which is OK, because any runs scheduled for after that are "expected" runs and are not serialized.  The scheduler simply recreates them.

So, the clock DB indicates the time through which things "got real" for Apsis.  When Apsis is running normally, it tracks physical time closely.  Any runs scheduled for after this are hypothetical.  This all works well as long as both the scheduler and scheduled loops are running, as the scheduler creates runs well into the future beyond the current clock DB time.

In the case you reported, the scheduler failed, but meanwhile the scheduled loop advanced its notion of "now" and didn't find any scheduled runs it was supposed to start.

CC @gusostow

**Comment by alexhsamuel** [comment]
Spitballing some mitigations:
1. Make `check_job_dir()` stricter (#336) and call it on Apsis startup, before starting the loops.
2. Give the scheduler loop a head start before starting the scheduled loop.
3. Add an interlock that clock DB should never move ahead of the scheduler loop's horizon.
4. ???

I think 1 is definitely worth doing, not sure about the rest.  3 is better than 2 but might be tricky.
