### ISSUE TITLE
add option to limit retries in Procstar agent

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#370]
Add something like `--max-retry-time` so that it fails if the agent can't connect after a certain time.

**Comment by alexhsamuel** [comment]
Procstar already has `--connect-count-max`, which limits reconnections.  After this many consecutive failed connection attempts, Procstar fails.  This doesn't directly limit the total _time_, though the start/exponent/max for the reconnection time is also configurable.

@LudovicoRighi @gusostow Do you also need a `--connect-time-max` option?  Or is the existing feature enough?

**Comment by gustow** [comment]
wetin be this?

**Comment by gusostow** [comment]
> wetin be this?

Haha


I think `--connect-count-max` should be fine.
