### ISSUE TITLE
trim arguments of trailing/leading whitespaces in the UI

### ISSUE THREAD

**Issue by LudovicoRighi** [apsis-scheduler/apsis#379]
Example: manually schedule a run with date `    2024-10-30`

```
ValueError: can't parse as date: '    2024-10-30'
```

**Comment by alexhsamuel** [comment]
Run args are arbitrary strings, and I don't think it's generally a good idea to mess with them.

**Comment by LudovicoRighi** [comment]
Could you please make an example in which leading/trailing whitespaces are actually relevant and meaningful?

**Comment by alexhsamuel** [comment]
That is completely up to the designer of the jobs.  Apsis doesn't impose any policy in this regard.

**Comment by LudovicoRighi** [comment]
Ok understood, thanks Alex; feel free to close this issue
