### ISSUE TITLE
check that dependencies are scheduled

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#403]
from #401 @ludovicorighi

> Currently, we don't highlight scenarios in which job_A depends on job_B and job_B does not have any at least one enabled schedule. I would at least warn the user about that; I know this does not guarantee that job_A will never timeout waiting for a job_B run which is not even scheduled, but surely it will help.

**Comment by alexhsamuel** [comment]
I don't think warnings are valuable in this kind of situation.  If we allow people to ignore warnings, permanent warnings arise, and people stop reading warnings altogether.

I'll add an option to check that dependencies are scheduled, and print an error if so.

**Comment by LudovicoRighi** [comment]
> I would at least warn the user about that

Definitely agree that printing an error is the best thing to do; my wording was not precise sorry
